/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline": "#64748B",
        "outline-variant": "#E2E8F0",
        "background": "#F8FAFC",
        "surface": "#F8FAFC",
        "surface-bright": "#FFFFFF",
        "surface-container-lowest": "#FFFFFF",
        "surface-container-low": "#F1F5F9",
        "surface-container": "#E2E8F0",
        "surface-container-high": "#E8EDF5",
        "surface-container-highest": "#CBD5E1",
        "surface-dim": "#E2E8F0",
        "surface-tint": "#E97F29",
        "inverse-surface": "#1A1F45",
        "inverse-on-surface": "#F8FAFC",
        "on-surface": "#0F172A",
        "on-surface-variant": "#64748B",
        "on-background": "#0F172A",

        /* Brand Primary: Expertise Navy Blue (#1A1F45) */
        "primary": "#1A1F45",
        "on-primary": "#FFFFFF",
        "primary-container": "#252B5C",
        "on-primary-container": "#CBD5E1",
        "primary-fixed": "#E7E9F4",
        "primary-fixed-dim": "#C8CCE6",
        "on-primary-fixed": "#1A1F45",
        "on-primary-fixed-variant": "#2D346B",
        "inverse-primary": "#A5B0DF",

        /* Brand Secondary: Expertise Signature Solar Orange (#E97F29) */
        "secondary": "#E97F29",
        "on-secondary": "#FFFFFF",
        "secondary-container": "#FFF3EA",
        "on-secondary-container": "#9A4603",
        "secondary-fixed": "#FDE8D7",
        "secondary-fixed-dim": "#F9CDB0",
        "on-secondary-fixed": "#703002",
        "on-secondary-fixed-variant": "#B85808",

        /* Brand Tertiary: Deep Indigo & Accents */
        "tertiary": "#2B3566",
        "on-tertiary": "#FFFFFF",
        "tertiary-container": "#EAEBF7",
        "on-tertiary-container": "#E97F29",
        "tertiary-fixed": "#E0E3F5",
        "tertiary-fixed-dim": "#BCC3E8",
        "on-tertiary-fixed": "#1A1F45",
        "on-tertiary-fixed-variant": "#222A54",

        /* Status colors */
        "error": "#DC2626",
        "error-container": "#FEE2E2",
        "on-error": "#FFFFFF",
        "on-error-container": "#991B1B",
        "success": "#16A34A",
        "success-container": "#DCFCE7",
        "on-success": "#FFFFFF",
        "on-success-container": "#166534",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "space-2xl": "2rem",
        "space-lg": "1rem",
        "gutter": "1rem",
        "space-sm": "0.5rem",
        "margin": "1rem",
        "margin-tablet": "1.5rem",
        "gutter-sm": "0.75rem",
        "space-xs": "0.25rem",
        "space-md": "0.75rem",
        "space-xl": "1.5rem",
      },
      fontFamily: {
        "data-mono": ["Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "currency-display": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md-medium": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "data-mono": ["13px", { lineHeight: "18px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-md": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["22px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "currency-display": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.03em", fontWeight: "600" }],
        "body-md-medium": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-sm": ["16px", { lineHeight: "22px", letterSpacing: "-0.005em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
